### ISSUE TITLE
Upgrade to prisma 4

### ISSUE THREAD

**Issue by exaby73** [risen228/nestjs-zod-prisma#8]
Are there any plans to upgrade to prisma v4?

**Comment by radaemon** [comment]
> Are there any plans to upgrade to prisma v4?

Does it not work properly in v4?

**Comment by exaby73** [comment]
Dependencies are incompatible unfortunately

**Comment by riccardo-ditosto-gellify** [comment]
I've tried updating the peerDependencies and the library still seems to work, tests are passing

https://github.com/risenforces/nestjs-zod-prisma/pull/9

I'm currently using it without any issue

**Comment by exaby73** [comment]
Hopefully this gets merged :D

**Comment by KeentDev** [comment]
+1. it's 2023 and waiting for this one to get merged

**Comment by richardanewman** [comment]
+1 on merging this

**Comment by risen228** [comment]
Done

**Comment by exaby73** [comment]
Prisma just got updated to V5 🙃
